---
# defaults file for roles/php

php_packages:
  - "php"

php_info: true

adminer:
  install: true
  path: "/usr/share/adminer"
  download: "https://github.com/vrana/adminer/releases/download/v4.6.2/adminer-4.6.2-mysql.php"


